Update mirror.yml

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -48,6 +48,8 @@ jobs:
 
       - name: Download the files
         run: wget -m --retry-connrefused --tries=20 --no-host-directories --directory-prefix="www" --exclude-directories="/wp-json,/wp-admin" --regex-type 'pcre' --reject-regex '.*\?(?!ver).*' --wait 1 https://chriskthomas.com/
+      - name: Download 404
+        run: wget --content-on-error --directory-prefix="www" https://chriskthomas.com/404.html || echo "Expexted error"
 
       #- name: Save the file attrs
       #  run: .github/bin/save-file-attrs.py save
